on: push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: pwd
            - run: npm install
            - run: npm run docs:build
            - uses: actions/upload-artifact@v3
              with:
                path: docs/.vitepress/dist     
                
    job2:
        needs: job1
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/download-artifact@v3
           
            
